src/Magnum/Audio/Listener.cpp
src/Magnum/Audio/PlayableGroup.h
src/Magnum/Audio/Test/ListenerTest.cpp

Hi @mosra !
I just started using my recent contribution to MagnumAudio myself and immediately found two bugs (very bad omen): Listener would crash if passed a empty playable group on update and PlayableGroup.h produces some weird compile errors when Playable.h is not included aswell.
This PR provides fixes for both issues.
Greetings, Squareys

Fixes to recent PlayableGroup and Listener

---

Doxyfile
doc/openal-support.dox
src/Magnum/Audio/Buffer.cpp
src/Magnum/Audio/Buffer.h
src/Magnum/Audio/CMakeLists.txt
src/Magnum/Audio/Context.cpp
src/Magnum/Audio/Context.h
src/Magnum/Audio/Extensions.h
src/Magnum/Audio/Renderer.cpp
src/Magnum/Audio/Renderer.h
src/Magnum/Audio/Test/CMakeLists.txt
src/Magnum/Audio/Test/ContextTest.cpp
src/Magnum/Audio/Test/RendererTest.cpp
src/Magnum/DebugTools/ShapeRenderer.h
src/Magnum/ResourceManager.h
src/MagnumExternal/OpenAL/CMakeLists.txt
src/MagnumExternal/OpenAL/extensions.h

Hi @mosra, Hi everybody!
here is a work-in-progress pullrequest for anything related to Audio and OpenAL extension support.
TODOs:
- Not really anything to test.
Greetings, Squareys

OpenAL extension support

---

package/ci/appveyor.yml

Hi @mosra !
I just noticed that with the release of openal-1.17.0, the old download link for openal-1.16.0 is now
invalid. I updated the appveyor configuration to download 1.17.0.
Greetings, 
Squareys

package/ci: Update openal-soft download link.

---

src/Magnum/Audio/Context.cpp
src/Magnum/Audio/Context.h
src/Magnum/Audio/Renderer.cpp
src/Magnum/Audio/Renderer.h
src/Magnum/Audio/Test/ContextTest.cpp
src/Magnum/Audio/Test/RendererTest.cpp

Hi @mosra !
As promised on https://github.com/mosra/magnum/commit/fd624d605e417317976ce5d8aa44b1dca0013f58, here are the changed required for fixing the `hrtfStatus()` and `isHrtfEnabled()` methods, which have now moved to `Audio::Context`.
I also added a method to query the name of the hrtf in use.
Greetings,
Squareys

Audio: Hrtf Extension Support Fixes

---

src/Magnum/Platform/WindowlessWglApplication.cpp

I was getting this warning:
```plain
Scanning dependencies of target MagnumWindowlessWglApplication
[ 30%] Building CXX object src/Magnum/Platform/CMakeFiles/MagnumWindowlessWglApplication.dir/WindowlessWglApplication.cpp.obj
C:\Users\LB\Code\Magnum\build\Magnum-prefix\src\Magnum\src\Magnum\Platform\WindowlessWglApplication.cpp: In member function 'bool Magnum::Platform::WindowlessWglApplication::tryCreateContext(const Magnum::Platform::WindowlessWglApplication::Configuration&)':
C:\Users\LB\Code\Magnum\build\Magnum-prefix\src\Magnum\src\Magnum\Platform\WindowlessWglApplication.cpp:124:81: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
_renderingContext = wglCreateContextAttribsARB(_deviceContext, 0, attributes);
^
[ 30%] Linking CXX static library …
```

Fix 'zero as null pointer constant' warning

---

CMakeLists.txt
doc/building.dox
doc/cmake.dox
modules/FindGLFW.cmake
modules/FindMagnum.cmake
src/Magnum/Platform/CMakeLists.txt
src/Magnum/Platform/GlfwApplication.cpp
src/Magnum/Platform/GlfwApplication.h

Hi @mosra !
As discussed via gitter, I am implement an `Application` class based on GLFW, which supports creation of Vulkan contexts and therefore acts as a basis for the Magnum Vulkan implementation.
This already compiles, but is not enabled on ci. Since creating Vulkan contexts will only be supported in GLFW 3.2, which is not quite released yet, we will need to have the ci build it from https://github.com/glfw/glfw.
I have not tested this yet, it might be completely unusable. Other than that, you may want to have a look at naming/doc in the Key enum. Also, the main loop maybe.
Regards,
Squareys (Jonathan Hale)
TODO:
- ~~`tickEvent()`~~
- ~~@mosra shall I already add the context creation for Vulkan in this PR?~~ No.

Add GlfwApplication

---

Doxyfile

The doc was moved to khronos.org and the URL schema was changed. This is just a minor change, but these links are very handy while developing.
By the way, Magnum is a really great library. Keep up the good work!
Émile Grégoire

Fix href to OpenGL reference generated by Doxygen.

---

src/Magnum/Primitives/Cylinder.cpp

Fixed issue in Primitives::Cylinder::solid() where the last ring of faces wouldn't be created when using cap ends because of wrong offset.
See discussion here: https://gitter.im/mosra/magnum/archives/2017/03/23

Fix issue in Primitives::Cylinder::solid() with cap ends

---

modules/FindMagnum.cmake
src/Magnum/Platform/Sdl2Application.cpp
src/Magnum/Platform/Sdl2Application.h

Hi @mosra !
As mentioned, I am in the midst of moving the Sdl2Application to SDL2 for Emscripten (which removes alot of preprocessor branches).
Cheers, Jonathan

SDL2 Support when building for Emscripten

---

src/Magnum/Platform/GlfwApplication.h

Unfortunately, this pointer is checked when initializing the window, which makes the current release crash on application start. (Tested on VS2017 x64).
This small fix makes it work again. Not sure if you can easily get this into vcpkg, I am using a patched version locally right now.

Fix uninitialized pointer check in GlfwApplication.

---

src/MagnumExternal/OpenGL/GLES2/flextGLPlatformIOS.cpp
src/MagnumExternal/OpenGL/GLES3/flextGLPlatformIOS.cpp

These are the official include paths from Apple.

external: fix ES2 and ES3 include paths in iOS

---

CREDITS.md
doc/changelog.dox
src/Magnum/Math/Geometry/Intersection.h
src/Magnum/Math/Geometry/Test/CMakeLists.txt
src/Magnum/Math/Geometry/Test/IntersectionBenchmark.cpp
src/Magnum/Math/Geometry/Test/IntersectionTest.cpp

Hi @mosra !
As discussed per gitter, I started working on some culling math for a project at university. This pullrequest will add cleanly tested implementations for:
- ~~(Maybe `Math::Geometry::Intersection::triangleCone`, even though it's not really useful for culling)~~
Cheers, Jonathan
___
~~Plus batch intersection methods for:~~ (not part of this PR, progress backed up in [separate branch](https://github.com/Squareys/magnum/tree/culling-math-batch) )
- ~~Range - Cone~~
- ~~Sphere - Cone~~
~~Should I put them into a separate file? And/or separate `Batch::` namespace?~~ Discussed: `IntersectionBatch.h/.cpp` and same namespace.

Culling math

---

src/MagnumExternal/OpenGL/GL/flextGLPlatform.cpp
src/MagnumExternal/OpenGL/GL/flextGLPlatform.cpp.template

On multi gpu machines, `eglGetDisplay(EGL_DEFAULT_DISPLAY)` returns the display on GPU0.  If there is no valid EGL context on GPU0, `eglQueryString(display, EGL_VENDOR)` will return the null pointer and `std::strcmp(vendor, "NVIDIA") == 0` will segfault!
Instead, `eglGetCurrentDisplay` should be used instead as this returns the EGL display that has been most recently made current by `eglMakeCurrent`.
Pre-change:
```
I0126 07:50:04.296272 20411 WindowlessContext.cpp:86] [EGL] Detected 2 EGL devices
I0126 07:50:04.308815 20411 WindowlessContext.cpp:107] [EGL] Selected EGL device 1 for CUDA device 1
I0126 07:50:04.320178 20411 WindowlessContext.cpp:121] [EGL] Version: 1.4
I0126 07:50:04.320204 20411 WindowlessContext.cpp:122] [EGL] Vendor: NVIDIA
zsh: segmentation fault
```
Post-change:
``` …
```

Use eglGetCurrentDisplay

---

src/Magnum/Platform/GlfwApplication.cpp
src/Magnum/Platform/GlfwApplication.h
src/Magnum/Platform/Sdl2Application.cpp
src/Magnum/Platform/Sdl2Application.h

Now, it's possible to exit an application properly with a non-zero exit code.
On my end, I could only test the `Sdl2Application` version.
Review and feedback are welcome!

Platform: improve {Glfw,Sdl2}Application::exit().

---

Doxyfile-mcss
Doxyfile-public
src/Magnum/GL/Attribute.h
src/Magnum/Math/BoolVector.h
src/Magnum/Math/Matrix.h
src/Magnum/Math/Matrix3.h
src/Magnum/Math/Matrix4.h
src/Magnum/Math/Quaternion.h
src/Magnum/Math/RectangularMatrix.h
src/Magnum/Math/Unit.h
src/Magnum/Math/Vector.h
src/Magnum/Math/Vector2.h
src/Magnum/Math/Vector3.h
src/Magnum/Platform/CMakeLists.txt
src/Magnum/Platform/Sdl2Application.h

Using [pybind11](https://github.com/pybind/pybind11). 
TODO:

[WIP] Python bindings

---

src/Magnum/Platform/Implementation/DpiScaling.cpp

The function imported from the dll was being implicitly cast to a __cdecl calling convention, but the function itself can be in a __stdcall calling convention, depending on the Windows build environment.  Adding  WINAPI to the cast puts the function in the correct calling convention regardless of the Windows build environment.

Platform: fix DpiScaling to handle calling conventions properly on Windows.

---

src/Magnum/GL/Texture.h

Fixes the following compile error:
magnum/src/Magnum/GL/Texture.h:747:44: error: no member named 'imageSize' in 'Magnum::GL::AbstractTexture::DataHelper<2>'
return DataHelper<dimensions>::imageSize(*this, level);
^

GL: imageSize is not available for GLES < 3.1

---

src/Magnum/Platform/AbstractXApplication.cpp
src/Magnum/Platform/AbstractXApplication.h
src/Magnum/Platform/GlfwApplication.cpp
src/Magnum/Platform/GlfwApplication.h

This PR adds a `mainLoopIteration()` function to `AbstractXApplication` and `GlfwApplication` similar to the one that `Sdl2Application` has.

Modular applications

---

src/Magnum/GL/AbstractTexture.cpp
src/Magnum/GL/AbstractTexture.h

Hi @mosra !
As promised, here the PR for the ArrayView overrides in AbstractTexture.
I checked building with doxygen, that is still running, but seems to still be able to resolve references correctly. I removed a couple of todos that referenced doxygen in the process, though, so there might be errors further down the line.
I'll ping once that has run through.
Best, Jonathan

GL: Add ArrayView<AbstractTexture*> overrides to bind and bindImages

---

src/Magnum/Math/Swizzle.h

Tiny fix, to suppress that annoying warning.

Stop Swizzle.h(75): warning C4389: '==': signed/unsigned mismatch

---

doc/changelog.dox
src/Magnum/GL/Implementation/MeshState.cpp
src/Magnum/GL/Implementation/driverSpecific.cpp

This should finally fix all remaining Intel Windows driver issues. Hopefully. Or at least until the next major driver update.
@alanjfs @jay3d @Squareys @aspioupiou @ttnghia and everybody else who's on Windows, has access to an Intel GPU and is developing a more complex (ideally ImGui-based) app, I need your help :) this branch, and the two workarounds, listed as `intel-windows-crazy-broken-buffer-dsa` and `intel-windows-crazy-broken-vao-dsa`, should fix all currently known (to me, at least) rendering issues and *not* break anything else. I commited the former workaround to `master` about two weeks ago but that unfortunately uncovered other bugs in the driver, so to avoid this happening yet again, I need to be more careful and do it this way.
I'll be grateful if you can all confirm that …

GL: expand ARB_DSA blacklisting on Intel Windows drivers a bit further

---

doc/changelog.dox
src/Magnum/Trade/AbstractImporter.cpp
src/Magnum/Trade/AbstractImporter.h
src/Magnum/Trade/Test/AbstractImporterTest.cpp
src/MagnumPlugins/AnyImageImporter/AnyImageImporter.cpp
src/MagnumPlugins/AnyImageImporter/AnyImageImporter.h
src/MagnumPlugins/AnySceneImporter/AnySceneImporter.cpp
src/MagnumPlugins/AnySceneImporter/AnySceneImporter.h
src/MagnumPlugins/ObjImporter/ObjImporter.cpp
src/MagnumPlugins/TgaImporter/TgaImporter.cpp
src/MagnumPlugins/TgaImporter/TgaImporter.h

There's a new level option in each `imageND()` API, plus an `imageNDLevelCount()` query to get image level count. The level defaults to 0, in which case it behaves exactly like before. For levels above 0, the abstract importer checks against the reported level count and asserts if it's out of bounds.
Things left to do:
@Squareys since you're working on mosra/magnum-plugins#62, could you have a quick look at this to see if it fits your expectations or needs design changes? Thanks! :pray:

Trade: support mip levels in image import

---

doc/changelog.dox
src/Magnum/Platform/GlfwApplication.cpp

Interestingly enough this went unnoticed since the very first implementation in 2016.
While I'm pretty sure this works, I'm not sure about possible bad interactions, so I'll merge to master only after I have enough confirmations that this still works as expected. Testers welcome, thanks in advance :+1: 
Cc: @Squareys

Avoid using 100% CPU in an idle GlfwApplication

---

src/Magnum/Platform/WindowlessEglApplication.cpp
src/Magnum/Platform/WindowlessEglApplication.h

Add support for CUDA device selection to Magnum's EGL context.  When using `WindowlessEglApplication`, this can be specified via `--magnum-cuda-device`.  Otherwise, whether or not a device is a CUDA device is specified by `setDeviceIsCuda()`.
@mosra Does the CI have an NV gpu to test this with?

CUDA device selection support

---

src/Magnum/Math/Functions.h
src/Magnum/Math/Test/FunctionsTest.cpp

This adds `Math::fmod()` to calculate a floating point division remainder for scalar and vector Math types by wrapping `std::fmod`.
Not entirely sure about the docs portion and especially the Latex (is `\operatorname` supported?).

Math: add fmod function

---

doc/platforms-html5.dox
src/Magnum/Platform/EmscriptenApplication.cpp
src/Magnum/Platform/EmscriptenApplication.h
src/Magnum/Platform/EmscriptenApplication.js
src/Magnum/Platform/Sdl2Application.cpp
src/Magnum/Platform/Sdl2Application.h
src/Magnum/Platform/Test/EmscriptenApplicationTest.cpp
src/Magnum/Platform/Test/EmscriptenApplicationTest.html
src/Magnum/Platform/Test/Sdl2ApplicationTest.cpp
src/Magnum/Platform/Test/Sdl2ApplicationTest.html
src/Magnum/Platform/Test/WindowlessEglApplicationTest.html
src/Magnum/Platform/WebApplication.css
src/Magnum/Platform/WindowlessEmscriptenApplication.js

Prerequisite / related to #480.
- changes the CSS to use classes instead of IDs for styling, allowing to style more than one canvas on the same page without having to patch / copy `WebApplication.css`
- changes `setContainerCssClass()` to not use a hardcoded `#container` element but instead go up from the `<canvas>` to the first `.mn-container` (which, again, should make more canvases work)
- changes `Module` to not use hardcoded `#status` and `#status-description` IDs but instead fetch them from `Module.status` and `Module.statusDescription` that are easier to be overriden from the HTML
~~What's still not great:~~ All handled by #480 now:
Cc: @pezcode

CSS changes to allow multiple Emscripten canvases on one page

---

src/Magnum/Math/Intersection.h
src/Magnum/Math/Test/IntersectionTest.cpp

This pull request introduces a slab algorithm for efficient ray range intersection tests.
I took the algorithm presented in listing one in this [paper](http://jcgt.org/published/0007/03/04/) (which I discovered through [this](https://medium.com/@bromanz/another-view-on-the-classic-ray-aabb-intersection-algorithm-for-bvh-traversal-41125138b525) blogpost).

add ray range interection algorithm

---

src/Magnum/Platform/WindowlessCglApplication.cpp
src/Magnum/Platform/WindowlessCglApplication.h
src/Magnum/Platform/WindowlessEglApplication.cpp
src/Magnum/Platform/WindowlessEglApplication.h
src/Magnum/Platform/WindowlessGlxApplication.cpp
src/Magnum/Platform/WindowlessGlxApplication.h

This PR adds the possibility to release a windowless context inside the following apps:
- `EglWindowlessApplication`
- `CglWindowlessApplication`
- `GlxWindowlessApplication`
I have tested `Glx` and it compiles/works like a charm. I will soon test `Egl`. I have no way of testing `Cgl`. Also I have no way of testing it in other windowless apps.
Let me know of your comments..

[WindowLessApps]: add release option to contexts [egl,cgl,glx for linux]

---

src/MagnumPlugins/AnyImageImporter/AnyImageImporter.cpp
src/MagnumPlugins/AnyImageImporter/Test/AnyImageImporterTest.cpp

I needed this to test the cube map example with KTX files, feel free to merge or copypaste once KtxImporter got added.

AnyImageImporter: detect KTX2

---

doc/changelog.dox
src/Magnum/GL/Implementation/MeshState.cpp
src/Magnum/GL/Implementation/driverSpecific.cpp
src/Magnum/GL/Mesh.cpp
src/Magnum/GL/Mesh.h
src/Magnum/GL/Test/MeshGLTest.cpp

Because the bugs keep piling up faster than I'm able to find solutions, sigh.
The original problem, as reported by @kleisauke: Pressing <kbd>S</kbd> and shooting the first sphere in the [web Bullet example](https://magnum.graphics/showcase/bullet/) gives a `Vertex buffer is not big enough for the draw call.` WebGL error -- an ANGLE-specific bug where instanced attributes don't get bounds-checked properly with non-instanced `glDraw*()`. The workaround is to use `glDraw*Instanced()` unconditionally if instanced attributes are present. 
I'm hesitant to do this unconditionally because who knows what other bugs or perf drops on other implementations / ANGLE backends this would uncover.
The workaround implementation is correct and was verified to work, however I'm stuck on crafting a regression …

GL: new "angle-instanced-attributes-always-draw-instanced" workaround
